service: WeatherStatus
provider:
  name: aws
  profile: 
  runtime: nodejs12.x
  region: ap-southeast-1

plugins:
  - serverless-offline
  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - .env

functions:
  hello:
    handler: handler.index
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /
          method: get
